cors:
  originPatterns: http://localhost:8080,http://velascoluan.com.br
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/formula1?useTimezone=true&serverTimezone=UTC
    username: root
    password: adm123
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

springdoc:
  pathToMatch: api/v1/**
  swagger-ui:
    use-root-path: true